// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// log_EXP_pi
arma::rowvec log_EXP_pi(arma::rowvec a_k, arma::rowvec b_k);
RcppExport SEXP _Poser_log_EXP_pi(SEXP a_kSEXP, SEXP b_kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec >::type a_k(a_kSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type b_k(b_kSEXP);
    rcpp_result_gen = Rcpp::wrap(log_EXP_pi(a_k, b_k));
    return rcpp_result_gen;
END_RCPP
}
// create_antiRHO
arma::mat create_antiRHO(arma::mat RHO, arma::field<arma::uvec> NN_inds);
RcppExport SEXP _Poser_create_antiRHO(SEXP RHOSEXP, SEXP NN_indsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type RHO(RHOSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::uvec> >::type NN_inds(NN_indsSEXP);
    rcpp_result_gen = Rcpp::wrap(create_antiRHO(RHO, NN_inds));
    return rcpp_result_gen;
END_RCPP
}
// log_beta_normconts_PL
double log_beta_normconts_PL(arma::mat antiRHO, double E_beta);
RcppExport SEXP _Poser_log_beta_normconts_PL(SEXP antiRHOSEXP, SEXP E_betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type antiRHO(antiRHOSEXP);
    Rcpp::traits::input_parameter< double >::type E_beta(E_betaSEXP);
    rcpp_result_gen = Rcpp::wrap(log_beta_normconts_PL(antiRHO, E_beta));
    return rcpp_result_gen;
END_RCPP
}
// upd_THETA_cpp
arma::mat upd_THETA_cpp(const arma::mat& Y, const arma::cube& XI, const arma::mat& RHO, const arma::mat& mkcd0);
RcppExport SEXP _Poser_upd_THETA_cpp(SEXP YSEXP, SEXP XISEXP, SEXP RHOSEXP, SEXP mkcd0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type XI(XISEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type RHO(RHOSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mkcd0(mkcd0SEXP);
    rcpp_result_gen = Rcpp::wrap(upd_THETA_cpp(Y, XI, RHO, mkcd0));
    return rcpp_result_gen;
END_RCPP
}
// upd_Vk_cpp
arma::mat upd_Vk_cpp(const double& a_tilde0_DP, const double& b_tilde0_DP, const arma::mat RHO);
RcppExport SEXP _Poser_upd_Vk_cpp(SEXP a_tilde0_DPSEXP, SEXP b_tilde0_DPSEXP, SEXP RHOSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type a_tilde0_DP(a_tilde0_DPSEXP);
    Rcpp::traits::input_parameter< const double& >::type b_tilde0_DP(b_tilde0_DPSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type RHO(RHOSEXP);
    rcpp_result_gen = Rcpp::wrap(upd_Vk_cpp(a_tilde0_DP, b_tilde0_DP, RHO));
    return rcpp_result_gen;
END_RCPP
}
// upd_alpha_DP
arma::rowvec upd_alpha_DP(const arma::rowvec& a_tilde_Vk, const arma::rowvec& b_tilde_Vk, const arma::rowvec& conc_hyper);
RcppExport SEXP _Poser_upd_alpha_DP(SEXP a_tilde_VkSEXP, SEXP b_tilde_VkSEXP, SEXP conc_hyperSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::rowvec& >::type a_tilde_Vk(a_tilde_VkSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type b_tilde_Vk(b_tilde_VkSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type conc_hyper(conc_hyperSEXP);
    rcpp_result_gen = Rcpp::wrap(upd_alpha_DP(a_tilde_Vk, b_tilde_Vk, conc_hyper));
    return rcpp_result_gen;
END_RCPP
}
// elbo_p_C_onlyPotts
double elbo_p_C_onlyPotts(arma::mat RHO, arma::mat antiRHO, double beta_potts);
RcppExport SEXP _Poser_elbo_p_C_onlyPotts(SEXP RHOSEXP, SEXP antiRHOSEXP, SEXP beta_pottsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type RHO(RHOSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type antiRHO(antiRHOSEXP);
    Rcpp::traits::input_parameter< double >::type beta_potts(beta_pottsSEXP);
    rcpp_result_gen = Rcpp::wrap(elbo_p_C_onlyPotts(RHO, antiRHO, beta_potts));
    return rcpp_result_gen;
END_RCPP
}
// elbo_q_C_v2
double elbo_q_C_v2(arma::mat RHO);
RcppExport SEXP _Poser_elbo_q_C_v2(SEXP RHOSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type RHO(RHOSEXP);
    rcpp_result_gen = Rcpp::wrap(elbo_q_C_v2(RHO));
    return rcpp_result_gen;
END_RCPP
}
// elbo_diff_itemp
double elbo_diff_itemp(arma::mat RHO, arma::mat antiRHO, double itemp);
RcppExport SEXP _Poser_elbo_diff_itemp(SEXP RHOSEXP, SEXP antiRHOSEXP, SEXP itempSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type RHO(RHOSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type antiRHO(antiRHOSEXP);
    Rcpp::traits::input_parameter< double >::type itemp(itempSEXP);
    rcpp_result_gen = Rcpp::wrap(elbo_diff_itemp(RHO, antiRHO, itemp));
    return rcpp_result_gen;
END_RCPP
}
// POSE_fiSAN
Rcpp::List POSE_fiSAN(arma::mat Y, arma::field<arma::uvec> NN_inds, double itemp, arma::vec itemp_grid, int L, int K, arma::mat B0, arma::mat mkcd_0, arma::mat RHO_init, arma::cube XI_init, arma::rowvec conc_hyper, int nsim, int compute_elbo_every, double epsilon, int replicates_potts, bool verbose, int algo_itemp, bool estimate_itemp);
RcppExport SEXP _Poser_POSE_fiSAN(SEXP YSEXP, SEXP NN_indsSEXP, SEXP itempSEXP, SEXP itemp_gridSEXP, SEXP LSEXP, SEXP KSEXP, SEXP B0SEXP, SEXP mkcd_0SEXP, SEXP RHO_initSEXP, SEXP XI_initSEXP, SEXP conc_hyperSEXP, SEXP nsimSEXP, SEXP compute_elbo_everySEXP, SEXP epsilonSEXP, SEXP replicates_pottsSEXP, SEXP verboseSEXP, SEXP algo_itempSEXP, SEXP estimate_itempSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::uvec> >::type NN_inds(NN_indsSEXP);
    Rcpp::traits::input_parameter< double >::type itemp(itempSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type itemp_grid(itemp_gridSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type B0(B0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mkcd_0(mkcd_0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type RHO_init(RHO_initSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type XI_init(XI_initSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type conc_hyper(conc_hyperSEXP);
    Rcpp::traits::input_parameter< int >::type nsim(nsimSEXP);
    Rcpp::traits::input_parameter< int >::type compute_elbo_every(compute_elbo_everySEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< int >::type replicates_potts(replicates_pottsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type algo_itemp(algo_itempSEXP);
    Rcpp::traits::input_parameter< bool >::type estimate_itemp(estimate_itempSEXP);
    rcpp_result_gen = Rcpp::wrap(POSE_fiSAN(Y, NN_inds, itemp, itemp_grid, L, K, B0, mkcd_0, RHO_init, XI_init, conc_hyper, nsim, compute_elbo_every, epsilon, replicates_potts, verbose, algo_itemp, estimate_itemp));
    return rcpp_result_gen;
END_RCPP
}
// POSE_onlyPotts
Rcpp::List POSE_onlyPotts(arma::mat Y, arma::field<arma::uvec> NN_inds, double itemp, arma::vec itemp_grid, int L, int K, arma::mat B0, arma::mat mkcd_0, arma::mat RHO_init, arma::cube XI_init, int nsim, int compute_elbo_every, double epsilon, int replicates_potts, bool verbose, int algo_itemp, bool estimate_itemp);
RcppExport SEXP _Poser_POSE_onlyPotts(SEXP YSEXP, SEXP NN_indsSEXP, SEXP itempSEXP, SEXP itemp_gridSEXP, SEXP LSEXP, SEXP KSEXP, SEXP B0SEXP, SEXP mkcd_0SEXP, SEXP RHO_initSEXP, SEXP XI_initSEXP, SEXP nsimSEXP, SEXP compute_elbo_everySEXP, SEXP epsilonSEXP, SEXP replicates_pottsSEXP, SEXP verboseSEXP, SEXP algo_itempSEXP, SEXP estimate_itempSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::uvec> >::type NN_inds(NN_indsSEXP);
    Rcpp::traits::input_parameter< double >::type itemp(itempSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type itemp_grid(itemp_gridSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type B0(B0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mkcd_0(mkcd_0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type RHO_init(RHO_initSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type XI_init(XI_initSEXP);
    Rcpp::traits::input_parameter< int >::type nsim(nsimSEXP);
    Rcpp::traits::input_parameter< int >::type compute_elbo_every(compute_elbo_everySEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< int >::type replicates_potts(replicates_pottsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type algo_itemp(algo_itempSEXP);
    Rcpp::traits::input_parameter< bool >::type estimate_itemp(estimate_itempSEXP);
    rcpp_result_gen = Rcpp::wrap(POSE_onlyPotts(Y, NN_inds, itemp, itemp_grid, L, K, B0, mkcd_0, RHO_init, XI_init, nsim, compute_elbo_every, epsilon, replicates_potts, verbose, algo_itemp, estimate_itemp));
    return rcpp_result_gen;
END_RCPP
}
// SE_CAM
Rcpp::List SE_CAM(arma::mat Y, int L, int K, arma::mat mkcd_0, arma::mat RHO_init, arma::cube XI_init, arma::rowvec conc_hyper, int nsim, int compute_elbo_every, double epsilon, bool verbose);
RcppExport SEXP _Poser_SE_CAM(SEXP YSEXP, SEXP LSEXP, SEXP KSEXP, SEXP mkcd_0SEXP, SEXP RHO_initSEXP, SEXP XI_initSEXP, SEXP conc_hyperSEXP, SEXP nsimSEXP, SEXP compute_elbo_everySEXP, SEXP epsilonSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mkcd_0(mkcd_0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type RHO_init(RHO_initSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type XI_init(XI_initSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type conc_hyper(conc_hyperSEXP);
    Rcpp::traits::input_parameter< int >::type nsim(nsimSEXP);
    Rcpp::traits::input_parameter< int >::type compute_elbo_every(compute_elbo_everySEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(SE_CAM(Y, L, K, mkcd_0, RHO_init, XI_init, conc_hyper, nsim, compute_elbo_every, epsilon, verbose));
    return rcpp_result_gen;
END_RCPP
}
// SE_fSAN
Rcpp::List SE_fSAN(arma::mat Y, int L, int K, arma::rowvec A0, arma::mat B0, arma::mat mkcd_0, arma::mat RHO_init, arma::cube XI_init, int nsim, int compute_elbo_every, double epsilon, bool verbose);
RcppExport SEXP _Poser_SE_fSAN(SEXP YSEXP, SEXP LSEXP, SEXP KSEXP, SEXP A0SEXP, SEXP B0SEXP, SEXP mkcd_0SEXP, SEXP RHO_initSEXP, SEXP XI_initSEXP, SEXP nsimSEXP, SEXP compute_elbo_everySEXP, SEXP epsilonSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type A0(A0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type B0(B0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mkcd_0(mkcd_0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type RHO_init(RHO_initSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type XI_init(XI_initSEXP);
    Rcpp::traits::input_parameter< int >::type nsim(nsimSEXP);
    Rcpp::traits::input_parameter< int >::type compute_elbo_every(compute_elbo_everySEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(SE_fSAN(Y, L, K, A0, B0, mkcd_0, RHO_init, XI_init, nsim, compute_elbo_every, epsilon, verbose));
    return rcpp_result_gen;
END_RCPP
}
// SE_fiSAN
Rcpp::List SE_fiSAN(arma::mat Y, int L, int K, arma::mat B0, arma::mat mkcd_0, arma::mat RHO_init, arma::cube XI_init, arma::rowvec conc_hyper, int nsim, int compute_elbo_every, double epsilon, bool verbose);
RcppExport SEXP _Poser_SE_fiSAN(SEXP YSEXP, SEXP LSEXP, SEXP KSEXP, SEXP B0SEXP, SEXP mkcd_0SEXP, SEXP RHO_initSEXP, SEXP XI_initSEXP, SEXP conc_hyperSEXP, SEXP nsimSEXP, SEXP compute_elbo_everySEXP, SEXP epsilonSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type B0(B0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mkcd_0(mkcd_0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type RHO_init(RHO_initSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type XI_init(XI_initSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type conc_hyper(conc_hyperSEXP);
    Rcpp::traits::input_parameter< int >::type nsim(nsimSEXP);
    Rcpp::traits::input_parameter< int >::type compute_elbo_every(compute_elbo_everySEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(SE_fiSAN(Y, L, K, B0, mkcd_0, RHO_init, XI_init, conc_hyper, nsim, compute_elbo_every, epsilon, verbose));
    return rcpp_result_gen;
END_RCPP
}
// EQ66
double EQ66(arma::mat RHO, arma::field<arma::uvec> NN_inds);
RcppExport SEXP _Poser_EQ66(SEXP RHOSEXP, SEXP NN_indsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type RHO(RHOSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::uvec> >::type NN_inds(NN_indsSEXP);
    rcpp_result_gen = Rcpp::wrap(EQ66(RHO, NN_inds));
    return rcpp_result_gen;
END_RCPP
}
// p_MF
arma::mat p_MF(double itemp, arma::mat antiRHO, arma::rowvec log_e_pi);
RcppExport SEXP _Poser_p_MF(SEXP itempSEXP, SEXP antiRHOSEXP, SEXP log_e_piSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type itemp(itempSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type antiRHO(antiRHOSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type log_e_pi(log_e_piSEXP);
    rcpp_result_gen = Rcpp::wrap(p_MF(itemp, antiRHO, log_e_pi));
    return rcpp_result_gen;
END_RCPP
}
// create_pMF
arma::mat create_pMF(double beta, arma::mat antiRHO, arma::rowvec log_e_pi);
RcppExport SEXP _Poser_create_pMF(SEXP betaSEXP, SEXP antiRHOSEXP, SEXP log_e_piSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type antiRHO(antiRHOSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type log_e_pi(log_e_piSEXP);
    rcpp_result_gen = Rcpp::wrap(create_pMF(beta, antiRHO, log_e_pi));
    return rcpp_result_gen;
END_RCPP
}
// bisection_LU2
double bisection_LU2(arma::mat RHO, arma::field<arma::uvec> NN_inds, arma::rowvec log_e_pi, double low, double upp, int N_sims);
RcppExport SEXP _Poser_bisection_LU2(SEXP RHOSEXP, SEXP NN_indsSEXP, SEXP log_e_piSEXP, SEXP lowSEXP, SEXP uppSEXP, SEXP N_simsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type RHO(RHOSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::uvec> >::type NN_inds(NN_indsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type log_e_pi(log_e_piSEXP);
    Rcpp::traits::input_parameter< double >::type low(lowSEXP);
    Rcpp::traits::input_parameter< double >::type upp(uppSEXP);
    Rcpp::traits::input_parameter< int >::type N_sims(N_simsSEXP);
    rcpp_result_gen = Rcpp::wrap(bisection_LU2(RHO, NN_inds, log_e_pi, low, upp, N_sims));
    return rcpp_result_gen;
END_RCPP
}
// est_itemp_PL2
double est_itemp_PL2(arma::mat RHO, arma::mat antiRHO, arma::vec itemp_grid);
RcppExport SEXP _Poser_est_itemp_PL2(SEXP RHOSEXP, SEXP antiRHOSEXP, SEXP itemp_gridSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type RHO(RHOSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type antiRHO(antiRHOSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type itemp_grid(itemp_gridSEXP);
    rcpp_result_gen = Rcpp::wrap(est_itemp_PL2(RHO, antiRHO, itemp_grid));
    return rcpp_result_gen;
END_RCPP
}
// est_itemp_PL2_withpi
double est_itemp_PL2_withpi(arma::mat RHO, arma::mat antiRHO, arma::rowvec ElogPi, arma::vec itemp_grid);
RcppExport SEXP _Poser_est_itemp_PL2_withpi(SEXP RHOSEXP, SEXP antiRHOSEXP, SEXP ElogPiSEXP, SEXP itemp_gridSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type RHO(RHOSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type antiRHO(antiRHOSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type ElogPi(ElogPiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type itemp_grid(itemp_gridSEXP);
    rcpp_result_gen = Rcpp::wrap(est_itemp_PL2_withpi(RHO, antiRHO, ElogPi, itemp_grid));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Poser_log_EXP_pi", (DL_FUNC) &_Poser_log_EXP_pi, 2},
    {"_Poser_create_antiRHO", (DL_FUNC) &_Poser_create_antiRHO, 2},
    {"_Poser_log_beta_normconts_PL", (DL_FUNC) &_Poser_log_beta_normconts_PL, 2},
    {"_Poser_upd_THETA_cpp", (DL_FUNC) &_Poser_upd_THETA_cpp, 4},
    {"_Poser_upd_Vk_cpp", (DL_FUNC) &_Poser_upd_Vk_cpp, 3},
    {"_Poser_upd_alpha_DP", (DL_FUNC) &_Poser_upd_alpha_DP, 3},
    {"_Poser_elbo_p_C_onlyPotts", (DL_FUNC) &_Poser_elbo_p_C_onlyPotts, 3},
    {"_Poser_elbo_q_C_v2", (DL_FUNC) &_Poser_elbo_q_C_v2, 1},
    {"_Poser_elbo_diff_itemp", (DL_FUNC) &_Poser_elbo_diff_itemp, 3},
    {"_Poser_POSE_fiSAN", (DL_FUNC) &_Poser_POSE_fiSAN, 18},
    {"_Poser_POSE_onlyPotts", (DL_FUNC) &_Poser_POSE_onlyPotts, 17},
    {"_Poser_SE_CAM", (DL_FUNC) &_Poser_SE_CAM, 11},
    {"_Poser_SE_fSAN", (DL_FUNC) &_Poser_SE_fSAN, 12},
    {"_Poser_SE_fiSAN", (DL_FUNC) &_Poser_SE_fiSAN, 12},
    {"_Poser_EQ66", (DL_FUNC) &_Poser_EQ66, 2},
    {"_Poser_p_MF", (DL_FUNC) &_Poser_p_MF, 3},
    {"_Poser_create_pMF", (DL_FUNC) &_Poser_create_pMF, 3},
    {"_Poser_bisection_LU2", (DL_FUNC) &_Poser_bisection_LU2, 6},
    {"_Poser_est_itemp_PL2", (DL_FUNC) &_Poser_est_itemp_PL2, 3},
    {"_Poser_est_itemp_PL2_withpi", (DL_FUNC) &_Poser_est_itemp_PL2_withpi, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_Poser(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
