# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log_EXP_pi <- function(a_k, b_k) {
    .Call(`_Poser_log_EXP_pi`, a_k, b_k)
}

create_antiRHO <- function(RHO, NN_inds) {
    .Call(`_Poser_create_antiRHO`, RHO, NN_inds)
}

log_beta_normconts_PL <- function(antiRHO, E_beta) {
    .Call(`_Poser_log_beta_normconts_PL`, antiRHO, E_beta)
}

upd_THETA_cpp <- function(Y, XI, RHO, mkcd0) {
    .Call(`_Poser_upd_THETA_cpp`, Y, XI, RHO, mkcd0)
}

upd_Vk_cpp <- function(a_tilde0_DP, b_tilde0_DP, RHO) {
    .Call(`_Poser_upd_Vk_cpp`, a_tilde0_DP, b_tilde0_DP, RHO)
}

upd_alpha_DP <- function(a_tilde_Vk, b_tilde_Vk, conc_hyper) {
    .Call(`_Poser_upd_alpha_DP`, a_tilde_Vk, b_tilde_Vk, conc_hyper)
}

elbo_p_C_onlyPotts <- function(RHO, antiRHO, beta_potts) {
    .Call(`_Poser_elbo_p_C_onlyPotts`, RHO, antiRHO, beta_potts)
}

elbo_q_C_v2 <- function(RHO) {
    .Call(`_Poser_elbo_q_C_v2`, RHO)
}

elbo_diff_itemp <- function(RHO, antiRHO, itemp) {
    .Call(`_Poser_elbo_diff_itemp`, RHO, antiRHO, itemp)
}

POSE_fiSAN <- function(Y, NN_inds, itemp, itemp_grid, L, K, B0, mkcd_0, RHO_init, XI_init, conc_hyper, nsim = 100L, compute_elbo_every = 1L, epsilon = .001, replicates_potts = 5L, verbose = TRUE, algo_itemp = 0L, estimate_itemp = FALSE) {
    .Call(`_Poser_POSE_fiSAN`, Y, NN_inds, itemp, itemp_grid, L, K, B0, mkcd_0, RHO_init, XI_init, conc_hyper, nsim, compute_elbo_every, epsilon, replicates_potts, verbose, algo_itemp, estimate_itemp)
}

POSE_onlyPotts <- function(Y, NN_inds, itemp, itemp_grid, L, K, B0, mkcd_0, RHO_init, XI_init, nsim = 100L, compute_elbo_every = 1L, epsilon = .001, replicates_potts = 5L, verbose = 1L, algo_itemp = 0L, estimate_itemp = 0L) {
    .Call(`_Poser_POSE_onlyPotts`, Y, NN_inds, itemp, itemp_grid, L, K, B0, mkcd_0, RHO_init, XI_init, nsim, compute_elbo_every, epsilon, replicates_potts, verbose, algo_itemp, estimate_itemp)
}

SE_CAM <- function(Y, L, K, mkcd_0, RHO_init, XI_init, conc_hyper, nsim = 100L, compute_elbo_every = 1L, epsilon = .001, verbose = TRUE) {
    .Call(`_Poser_SE_CAM`, Y, L, K, mkcd_0, RHO_init, XI_init, conc_hyper, nsim, compute_elbo_every, epsilon, verbose)
}

SE_fSAN <- function(Y, L, K, A0, B0, mkcd_0, RHO_init, XI_init, nsim = 100L, compute_elbo_every = 1L, epsilon = .001, verbose = TRUE) {
    .Call(`_Poser_SE_fSAN`, Y, L, K, A0, B0, mkcd_0, RHO_init, XI_init, nsim, compute_elbo_every, epsilon, verbose)
}

SE_fiSAN <- function(Y, L, K, B0, mkcd_0, RHO_init, XI_init, conc_hyper, nsim = 100L, compute_elbo_every = 1L, epsilon = .001, verbose = TRUE) {
    .Call(`_Poser_SE_fiSAN`, Y, L, K, B0, mkcd_0, RHO_init, XI_init, conc_hyper, nsim, compute_elbo_every, epsilon, verbose)
}

EQ66 <- function(RHO, NN_inds) {
    .Call(`_Poser_EQ66`, RHO, NN_inds)
}

p_MF <- function(itemp, antiRHO, log_e_pi) {
    .Call(`_Poser_p_MF`, itemp, antiRHO, log_e_pi)
}

create_pMF <- function(beta, antiRHO, log_e_pi) {
    .Call(`_Poser_create_pMF`, beta, antiRHO, log_e_pi)
}

bisection_LU2 <- function(RHO, NN_inds, log_e_pi, low, upp, N_sims) {
    .Call(`_Poser_bisection_LU2`, RHO, NN_inds, log_e_pi, low, upp, N_sims)
}

est_itemp_PL2 <- function(RHO, antiRHO, itemp_grid) {
    .Call(`_Poser_est_itemp_PL2`, RHO, antiRHO, itemp_grid)
}

est_itemp_PL2_withpi <- function(RHO, antiRHO, ElogPi, itemp_grid) {
    .Call(`_Poser_est_itemp_PL2_withpi`, RHO, antiRHO, ElogPi, itemp_grid)
}

