# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

create_antiRHO <- function(RHO, NN_inds) {
    .Call(`_POSEIDON_create_antiRHO`, RHO, NN_inds)
}

log_beta_normconts_PL <- function(antiRHO, E_beta) {
    .Call(`_POSEIDON_log_beta_normconts_PL`, antiRHO, E_beta)
}

log_beta_normconts_PL2 <- function(antiRHO, E_beta) {
    .Call(`_POSEIDON_log_beta_normconts_PL2`, antiRHO, E_beta)
}

E_log_beta_row <- function(a, b) {
    .Call(`_POSEIDON_E_log_beta_row`, a, b)
}

upd_RHO_cpp_fusion <- function(Y, RHO, X, mkcd_starcube, NN_inds, itemp, E_log_pi_k, reps, D, J, K, L) {
    .Call(`_POSEIDON_upd_RHO_cpp_fusion`, Y, RHO, X, mkcd_starcube, NN_inds, itemp, E_log_pi_k, reps, D, J, K, L)
}

upd_RHO_cpp_fusion_onlyPi <- function(Y, X, mkcd_starcube, E_log_pi_k, D, J, K, L) {
    .Call(`_POSEIDON_upd_RHO_cpp_fusion_onlyPi`, Y, X, mkcd_starcube, E_log_pi_k, D, J, K, L)
}

upd_RHO_cpp_fusion_onlyPotts <- function(Y, RHO, X, mkcd_starcube, NN_inds, itemp, reps, D, J, K, L) {
    .Call(`_POSEIDON_upd_RHO_cpp_fusion_onlyPotts`, Y, RHO, X, mkcd_starcube, NN_inds, itemp, reps, D, J, K, L)
}

upd_Vk_cpp <- function(a_tilde0_DP, b_tilde0_DP, RHO) {
    .Call(`_POSEIDON_upd_Vk_cpp`, a_tilde0_DP, b_tilde0_DP, RHO)
}

elbo_diff_R_fusion <- function(XI, beta_star_cube, D) {
    .Call(`_POSEIDON_elbo_diff_R_fusion`, XI, beta_star_cube, D)
}

elbo_p_Y_fusion <- function(Y, XI, RHO, mkcd_star, D) {
    .Call(`_POSEIDON_elbo_p_Y_fusion`, Y, XI, RHO, mkcd_star, D)
}

POSEIDON_cpp_fiSAN <- function(Y_list, NN_inds, itemp, itemp_grid, L, K, D, B0, mkcd_0, RHO_init, XI_init, conc_hyper, nsim = 100L, compute_elbo_every = 1L, epsilon = .001, verbose = TRUE, replicates_potts = 5L, estimate_itemp = FALSE) {
    .Call(`_POSEIDON_POSEIDON_cpp_fiSAN`, Y_list, NN_inds, itemp, itemp_grid, L, K, D, B0, mkcd_0, RHO_init, XI_init, conc_hyper, nsim, compute_elbo_every, epsilon, verbose, replicates_potts, estimate_itemp)
}

POSEIDON_cpp_onlyPotts <- function(Y_list, NN_inds, itemp, itemp_grid, L, K, B0, mkcd_0, RHO_init, XI_init, nsim = 100L, compute_elbo_every = 1L, epsilon = .001, verbose = TRUE, replicates_potts = 5L, estimate_itemp = FALSE) {
    .Call(`_POSEIDON_POSEIDON_cpp_onlyPotts`, Y_list, NN_inds, itemp, itemp_grid, L, K, B0, mkcd_0, RHO_init, XI_init, nsim, compute_elbo_every, epsilon, verbose, replicates_potts, estimate_itemp)
}

POSEIDON_cpp_onlyfiSAN <- function(Y_list, L, K, D, B0, mkcd_0, RHO_init, XI_init, conc_hyper, nsim = 100L, compute_elbo_every = 1L, epsilon = .001, verbose = TRUE, replicates_potts = 5L, estimate_itemp = FALSE) {
    .Call(`_POSEIDON_POSEIDON_cpp_onlyfiSAN`, Y_list, L, K, D, B0, mkcd_0, RHO_init, XI_init, conc_hyper, nsim, compute_elbo_every, epsilon, verbose, replicates_potts, estimate_itemp)
}

EQ66 <- function(RHO, NN_inds) {
    .Call(`_POSEIDON_EQ66`, RHO, NN_inds)
}

p_MF <- function(itemp, antiRHO, log_e_pi) {
    .Call(`_POSEIDON_p_MF`, itemp, antiRHO, log_e_pi)
}

create_pMF <- function(beta, antiRHO, log_e_pi) {
    .Call(`_POSEIDON_create_pMF`, beta, antiRHO, log_e_pi)
}

bisection_LU2 <- function(RHO, NN_inds, log_e_pi, low, upp, N_sims) {
    .Call(`_POSEIDON_bisection_LU2`, RHO, NN_inds, log_e_pi, low, upp, N_sims)
}

est_itemp_PL2 <- function(RHO, antiRHO, itemp_grid) {
    .Call(`_POSEIDON_est_itemp_PL2`, RHO, antiRHO, itemp_grid)
}

est_itemp_PL2_withpi <- function(RHO, antiRHO, ElogPi, itemp_grid) {
    .Call(`_POSEIDON_est_itemp_PL2_withpi`, RHO, antiRHO, ElogPi, itemp_grid)
}

