// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// create_antiRHO
arma::mat create_antiRHO(arma::mat RHO, arma::field<arma::uvec> NN_inds);
RcppExport SEXP _POSEIDON_create_antiRHO(SEXP RHOSEXP, SEXP NN_indsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type RHO(RHOSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::uvec> >::type NN_inds(NN_indsSEXP);
    rcpp_result_gen = Rcpp::wrap(create_antiRHO(RHO, NN_inds));
    return rcpp_result_gen;
END_RCPP
}
// log_beta_normconts_PL
double log_beta_normconts_PL(arma::mat antiRHO, double E_beta);
RcppExport SEXP _POSEIDON_log_beta_normconts_PL(SEXP antiRHOSEXP, SEXP E_betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type antiRHO(antiRHOSEXP);
    Rcpp::traits::input_parameter< double >::type E_beta(E_betaSEXP);
    rcpp_result_gen = Rcpp::wrap(log_beta_normconts_PL(antiRHO, E_beta));
    return rcpp_result_gen;
END_RCPP
}
// log_beta_normconts_PL2
double log_beta_normconts_PL2(arma::mat antiRHO, double E_beta);
RcppExport SEXP _POSEIDON_log_beta_normconts_PL2(SEXP antiRHOSEXP, SEXP E_betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type antiRHO(antiRHOSEXP);
    Rcpp::traits::input_parameter< double >::type E_beta(E_betaSEXP);
    rcpp_result_gen = Rcpp::wrap(log_beta_normconts_PL2(antiRHO, E_beta));
    return rcpp_result_gen;
END_RCPP
}
// E_log_beta_row
arma::rowvec E_log_beta_row(arma::rowvec a, arma::rowvec b);
RcppExport SEXP _POSEIDON_E_log_beta_row(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec >::type a(aSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(E_log_beta_row(a, b));
    return rcpp_result_gen;
END_RCPP
}
// upd_RHO_cpp_fusion
arma::mat upd_RHO_cpp_fusion(arma::field<arma::mat> Y, arma::mat RHO, arma::field<arma::cube> X, arma::cube mkcd_starcube, arma::field<arma::uvec> NN_inds, double itemp, arma::rowvec E_log_pi_k, int reps, int const D, int const J, int const K, int const L);
RcppExport SEXP _POSEIDON_upd_RHO_cpp_fusion(SEXP YSEXP, SEXP RHOSEXP, SEXP XSEXP, SEXP mkcd_starcubeSEXP, SEXP NN_indsSEXP, SEXP itempSEXP, SEXP E_log_pi_kSEXP, SEXP repsSEXP, SEXP DSEXP, SEXP JSEXP, SEXP KSEXP, SEXP LSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::field<arma::mat> >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type RHO(RHOSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::cube> >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type mkcd_starcube(mkcd_starcubeSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::uvec> >::type NN_inds(NN_indsSEXP);
    Rcpp::traits::input_parameter< double >::type itemp(itempSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type E_log_pi_k(E_log_pi_kSEXP);
    Rcpp::traits::input_parameter< int >::type reps(repsSEXP);
    Rcpp::traits::input_parameter< int const >::type D(DSEXP);
    Rcpp::traits::input_parameter< int const >::type J(JSEXP);
    Rcpp::traits::input_parameter< int const >::type K(KSEXP);
    Rcpp::traits::input_parameter< int const >::type L(LSEXP);
    rcpp_result_gen = Rcpp::wrap(upd_RHO_cpp_fusion(Y, RHO, X, mkcd_starcube, NN_inds, itemp, E_log_pi_k, reps, D, J, K, L));
    return rcpp_result_gen;
END_RCPP
}
// upd_RHO_cpp_fusion_onlyPi
arma::mat upd_RHO_cpp_fusion_onlyPi(arma::field<arma::mat> Y, arma::field<arma::cube> X, arma::cube mkcd_starcube, arma::rowvec E_log_pi_k, int const D, int const J, int const K, int const L);
RcppExport SEXP _POSEIDON_upd_RHO_cpp_fusion_onlyPi(SEXP YSEXP, SEXP XSEXP, SEXP mkcd_starcubeSEXP, SEXP E_log_pi_kSEXP, SEXP DSEXP, SEXP JSEXP, SEXP KSEXP, SEXP LSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::field<arma::mat> >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::cube> >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type mkcd_starcube(mkcd_starcubeSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type E_log_pi_k(E_log_pi_kSEXP);
    Rcpp::traits::input_parameter< int const >::type D(DSEXP);
    Rcpp::traits::input_parameter< int const >::type J(JSEXP);
    Rcpp::traits::input_parameter< int const >::type K(KSEXP);
    Rcpp::traits::input_parameter< int const >::type L(LSEXP);
    rcpp_result_gen = Rcpp::wrap(upd_RHO_cpp_fusion_onlyPi(Y, X, mkcd_starcube, E_log_pi_k, D, J, K, L));
    return rcpp_result_gen;
END_RCPP
}
// upd_RHO_cpp_fusion_onlyPotts
arma::mat upd_RHO_cpp_fusion_onlyPotts(arma::field<arma::mat> Y, arma::mat RHO, arma::field<arma::cube> X, arma::cube mkcd_starcube, arma::field<arma::uvec> NN_inds, double itemp, int reps, int const D, int const J, int const K, int const L);
RcppExport SEXP _POSEIDON_upd_RHO_cpp_fusion_onlyPotts(SEXP YSEXP, SEXP RHOSEXP, SEXP XSEXP, SEXP mkcd_starcubeSEXP, SEXP NN_indsSEXP, SEXP itempSEXP, SEXP repsSEXP, SEXP DSEXP, SEXP JSEXP, SEXP KSEXP, SEXP LSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::field<arma::mat> >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type RHO(RHOSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::cube> >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type mkcd_starcube(mkcd_starcubeSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::uvec> >::type NN_inds(NN_indsSEXP);
    Rcpp::traits::input_parameter< double >::type itemp(itempSEXP);
    Rcpp::traits::input_parameter< int >::type reps(repsSEXP);
    Rcpp::traits::input_parameter< int const >::type D(DSEXP);
    Rcpp::traits::input_parameter< int const >::type J(JSEXP);
    Rcpp::traits::input_parameter< int const >::type K(KSEXP);
    Rcpp::traits::input_parameter< int const >::type L(LSEXP);
    rcpp_result_gen = Rcpp::wrap(upd_RHO_cpp_fusion_onlyPotts(Y, RHO, X, mkcd_starcube, NN_inds, itemp, reps, D, J, K, L));
    return rcpp_result_gen;
END_RCPP
}
// upd_Vk_cpp
arma::mat upd_Vk_cpp(double const a_tilde0_DP, double const b_tilde0_DP, arma::mat RHO);
RcppExport SEXP _POSEIDON_upd_Vk_cpp(SEXP a_tilde0_DPSEXP, SEXP b_tilde0_DPSEXP, SEXP RHOSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double const >::type a_tilde0_DP(a_tilde0_DPSEXP);
    Rcpp::traits::input_parameter< double const >::type b_tilde0_DP(b_tilde0_DPSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type RHO(RHOSEXP);
    rcpp_result_gen = Rcpp::wrap(upd_Vk_cpp(a_tilde0_DP, b_tilde0_DP, RHO));
    return rcpp_result_gen;
END_RCPP
}
// elbo_diff_R_fusion
double elbo_diff_R_fusion(arma::field<arma::cube> XI, arma::cube beta_star_cube, int const D);
RcppExport SEXP _POSEIDON_elbo_diff_R_fusion(SEXP XISEXP, SEXP beta_star_cubeSEXP, SEXP DSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::field<arma::cube> >::type XI(XISEXP);
    Rcpp::traits::input_parameter< arma::cube >::type beta_star_cube(beta_star_cubeSEXP);
    Rcpp::traits::input_parameter< int const >::type D(DSEXP);
    rcpp_result_gen = Rcpp::wrap(elbo_diff_R_fusion(XI, beta_star_cube, D));
    return rcpp_result_gen;
END_RCPP
}
// elbo_p_Y_fusion
double elbo_p_Y_fusion(arma::field<arma::mat> Y, arma::field<arma::cube> XI, arma::mat RHO, arma::cube mkcd_star, int const D);
RcppExport SEXP _POSEIDON_elbo_p_Y_fusion(SEXP YSEXP, SEXP XISEXP, SEXP RHOSEXP, SEXP mkcd_starSEXP, SEXP DSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::field<arma::mat> >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::cube> >::type XI(XISEXP);
    Rcpp::traits::input_parameter< arma::mat >::type RHO(RHOSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type mkcd_star(mkcd_starSEXP);
    Rcpp::traits::input_parameter< int const >::type D(DSEXP);
    rcpp_result_gen = Rcpp::wrap(elbo_p_Y_fusion(Y, XI, RHO, mkcd_star, D));
    return rcpp_result_gen;
END_RCPP
}
// POSEIDON_cpp_fiSAN
Rcpp::List POSEIDON_cpp_fiSAN(const arma::field<arma::mat>& Y_list, const arma::field<arma::uvec>& NN_inds, double itemp, arma::vec itemp_grid, int const L, int const K, int const D, arma::cube B0, arma::cube mkcd_0, arma::mat RHO_init, arma::field<arma::cube> XI_init, arma::rowvec conc_hyper, int nsim, int compute_elbo_every, double epsilon, bool verbose, int replicates_potts, bool estimate_itemp);
RcppExport SEXP _POSEIDON_POSEIDON_cpp_fiSAN(SEXP Y_listSEXP, SEXP NN_indsSEXP, SEXP itempSEXP, SEXP itemp_gridSEXP, SEXP LSEXP, SEXP KSEXP, SEXP DSEXP, SEXP B0SEXP, SEXP mkcd_0SEXP, SEXP RHO_initSEXP, SEXP XI_initSEXP, SEXP conc_hyperSEXP, SEXP nsimSEXP, SEXP compute_elbo_everySEXP, SEXP epsilonSEXP, SEXP verboseSEXP, SEXP replicates_pottsSEXP, SEXP estimate_itempSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::field<arma::mat>& >::type Y_list(Y_listSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::uvec>& >::type NN_inds(NN_indsSEXP);
    Rcpp::traits::input_parameter< double >::type itemp(itempSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type itemp_grid(itemp_gridSEXP);
    Rcpp::traits::input_parameter< int const >::type L(LSEXP);
    Rcpp::traits::input_parameter< int const >::type K(KSEXP);
    Rcpp::traits::input_parameter< int const >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type B0(B0SEXP);
    Rcpp::traits::input_parameter< arma::cube >::type mkcd_0(mkcd_0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type RHO_init(RHO_initSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::cube> >::type XI_init(XI_initSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type conc_hyper(conc_hyperSEXP);
    Rcpp::traits::input_parameter< int >::type nsim(nsimSEXP);
    Rcpp::traits::input_parameter< int >::type compute_elbo_every(compute_elbo_everySEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type replicates_potts(replicates_pottsSEXP);
    Rcpp::traits::input_parameter< bool >::type estimate_itemp(estimate_itempSEXP);
    rcpp_result_gen = Rcpp::wrap(POSEIDON_cpp_fiSAN(Y_list, NN_inds, itemp, itemp_grid, L, K, D, B0, mkcd_0, RHO_init, XI_init, conc_hyper, nsim, compute_elbo_every, epsilon, verbose, replicates_potts, estimate_itemp));
    return rcpp_result_gen;
END_RCPP
}
// POSEIDON_cpp_onlyPotts
Rcpp::List POSEIDON_cpp_onlyPotts(const arma::field<arma::mat>& Y_list, const arma::field<arma::uvec>& NN_inds, double itemp, arma::vec itemp_grid, int const L, int const K, arma::cube B0, arma::cube mkcd_0, arma::mat RHO_init, arma::field<arma::cube> XI_init, int nsim, int compute_elbo_every, double epsilon, bool verbose, int replicates_potts, bool estimate_itemp);
RcppExport SEXP _POSEIDON_POSEIDON_cpp_onlyPotts(SEXP Y_listSEXP, SEXP NN_indsSEXP, SEXP itempSEXP, SEXP itemp_gridSEXP, SEXP LSEXP, SEXP KSEXP, SEXP B0SEXP, SEXP mkcd_0SEXP, SEXP RHO_initSEXP, SEXP XI_initSEXP, SEXP nsimSEXP, SEXP compute_elbo_everySEXP, SEXP epsilonSEXP, SEXP verboseSEXP, SEXP replicates_pottsSEXP, SEXP estimate_itempSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::field<arma::mat>& >::type Y_list(Y_listSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::uvec>& >::type NN_inds(NN_indsSEXP);
    Rcpp::traits::input_parameter< double >::type itemp(itempSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type itemp_grid(itemp_gridSEXP);
    Rcpp::traits::input_parameter< int const >::type L(LSEXP);
    Rcpp::traits::input_parameter< int const >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type B0(B0SEXP);
    Rcpp::traits::input_parameter< arma::cube >::type mkcd_0(mkcd_0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type RHO_init(RHO_initSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::cube> >::type XI_init(XI_initSEXP);
    Rcpp::traits::input_parameter< int >::type nsim(nsimSEXP);
    Rcpp::traits::input_parameter< int >::type compute_elbo_every(compute_elbo_everySEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type replicates_potts(replicates_pottsSEXP);
    Rcpp::traits::input_parameter< bool >::type estimate_itemp(estimate_itempSEXP);
    rcpp_result_gen = Rcpp::wrap(POSEIDON_cpp_onlyPotts(Y_list, NN_inds, itemp, itemp_grid, L, K, B0, mkcd_0, RHO_init, XI_init, nsim, compute_elbo_every, epsilon, verbose, replicates_potts, estimate_itemp));
    return rcpp_result_gen;
END_RCPP
}
// POSEIDON_cpp_onlyfiSAN
Rcpp::List POSEIDON_cpp_onlyfiSAN(const arma::field<arma::mat>& Y_list, int const L, int const K, int const D, arma::cube B0, arma::cube mkcd_0, arma::mat RHO_init, arma::field<arma::cube> XI_init, arma::rowvec conc_hyper, int nsim, int compute_elbo_every, double epsilon, bool verbose, int replicates_potts, bool estimate_itemp);
RcppExport SEXP _POSEIDON_POSEIDON_cpp_onlyfiSAN(SEXP Y_listSEXP, SEXP LSEXP, SEXP KSEXP, SEXP DSEXP, SEXP B0SEXP, SEXP mkcd_0SEXP, SEXP RHO_initSEXP, SEXP XI_initSEXP, SEXP conc_hyperSEXP, SEXP nsimSEXP, SEXP compute_elbo_everySEXP, SEXP epsilonSEXP, SEXP verboseSEXP, SEXP replicates_pottsSEXP, SEXP estimate_itempSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::field<arma::mat>& >::type Y_list(Y_listSEXP);
    Rcpp::traits::input_parameter< int const >::type L(LSEXP);
    Rcpp::traits::input_parameter< int const >::type K(KSEXP);
    Rcpp::traits::input_parameter< int const >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type B0(B0SEXP);
    Rcpp::traits::input_parameter< arma::cube >::type mkcd_0(mkcd_0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type RHO_init(RHO_initSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::cube> >::type XI_init(XI_initSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type conc_hyper(conc_hyperSEXP);
    Rcpp::traits::input_parameter< int >::type nsim(nsimSEXP);
    Rcpp::traits::input_parameter< int >::type compute_elbo_every(compute_elbo_everySEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type replicates_potts(replicates_pottsSEXP);
    Rcpp::traits::input_parameter< bool >::type estimate_itemp(estimate_itempSEXP);
    rcpp_result_gen = Rcpp::wrap(POSEIDON_cpp_onlyfiSAN(Y_list, L, K, D, B0, mkcd_0, RHO_init, XI_init, conc_hyper, nsim, compute_elbo_every, epsilon, verbose, replicates_potts, estimate_itemp));
    return rcpp_result_gen;
END_RCPP
}
// EQ66
double EQ66(arma::mat RHO, arma::field<arma::uvec> NN_inds);
RcppExport SEXP _POSEIDON_EQ66(SEXP RHOSEXP, SEXP NN_indsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type RHO(RHOSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::uvec> >::type NN_inds(NN_indsSEXP);
    rcpp_result_gen = Rcpp::wrap(EQ66(RHO, NN_inds));
    return rcpp_result_gen;
END_RCPP
}
// p_MF
arma::mat p_MF(double itemp, arma::mat antiRHO, arma::rowvec log_e_pi);
RcppExport SEXP _POSEIDON_p_MF(SEXP itempSEXP, SEXP antiRHOSEXP, SEXP log_e_piSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type itemp(itempSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type antiRHO(antiRHOSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type log_e_pi(log_e_piSEXP);
    rcpp_result_gen = Rcpp::wrap(p_MF(itemp, antiRHO, log_e_pi));
    return rcpp_result_gen;
END_RCPP
}
// create_pMF
arma::mat create_pMF(double beta, arma::mat antiRHO, arma::rowvec log_e_pi);
RcppExport SEXP _POSEIDON_create_pMF(SEXP betaSEXP, SEXP antiRHOSEXP, SEXP log_e_piSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type antiRHO(antiRHOSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type log_e_pi(log_e_piSEXP);
    rcpp_result_gen = Rcpp::wrap(create_pMF(beta, antiRHO, log_e_pi));
    return rcpp_result_gen;
END_RCPP
}
// bisection_LU2
double bisection_LU2(arma::mat RHO, arma::field<arma::uvec> NN_inds, arma::rowvec log_e_pi, double low, double upp, int N_sims);
RcppExport SEXP _POSEIDON_bisection_LU2(SEXP RHOSEXP, SEXP NN_indsSEXP, SEXP log_e_piSEXP, SEXP lowSEXP, SEXP uppSEXP, SEXP N_simsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type RHO(RHOSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::uvec> >::type NN_inds(NN_indsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type log_e_pi(log_e_piSEXP);
    Rcpp::traits::input_parameter< double >::type low(lowSEXP);
    Rcpp::traits::input_parameter< double >::type upp(uppSEXP);
    Rcpp::traits::input_parameter< int >::type N_sims(N_simsSEXP);
    rcpp_result_gen = Rcpp::wrap(bisection_LU2(RHO, NN_inds, log_e_pi, low, upp, N_sims));
    return rcpp_result_gen;
END_RCPP
}
// est_itemp_PL2
double est_itemp_PL2(arma::mat RHO, arma::mat antiRHO, arma::vec itemp_grid);
RcppExport SEXP _POSEIDON_est_itemp_PL2(SEXP RHOSEXP, SEXP antiRHOSEXP, SEXP itemp_gridSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type RHO(RHOSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type antiRHO(antiRHOSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type itemp_grid(itemp_gridSEXP);
    rcpp_result_gen = Rcpp::wrap(est_itemp_PL2(RHO, antiRHO, itemp_grid));
    return rcpp_result_gen;
END_RCPP
}
// est_itemp_PL2_withpi
double est_itemp_PL2_withpi(arma::mat RHO, arma::mat antiRHO, arma::rowvec ElogPi, arma::vec itemp_grid);
RcppExport SEXP _POSEIDON_est_itemp_PL2_withpi(SEXP RHOSEXP, SEXP antiRHOSEXP, SEXP ElogPiSEXP, SEXP itemp_gridSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type RHO(RHOSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type antiRHO(antiRHOSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type ElogPi(ElogPiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type itemp_grid(itemp_gridSEXP);
    rcpp_result_gen = Rcpp::wrap(est_itemp_PL2_withpi(RHO, antiRHO, ElogPi, itemp_grid));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_POSEIDON_create_antiRHO", (DL_FUNC) &_POSEIDON_create_antiRHO, 2},
    {"_POSEIDON_log_beta_normconts_PL", (DL_FUNC) &_POSEIDON_log_beta_normconts_PL, 2},
    {"_POSEIDON_log_beta_normconts_PL2", (DL_FUNC) &_POSEIDON_log_beta_normconts_PL2, 2},
    {"_POSEIDON_E_log_beta_row", (DL_FUNC) &_POSEIDON_E_log_beta_row, 2},
    {"_POSEIDON_upd_RHO_cpp_fusion", (DL_FUNC) &_POSEIDON_upd_RHO_cpp_fusion, 12},
    {"_POSEIDON_upd_RHO_cpp_fusion_onlyPi", (DL_FUNC) &_POSEIDON_upd_RHO_cpp_fusion_onlyPi, 8},
    {"_POSEIDON_upd_RHO_cpp_fusion_onlyPotts", (DL_FUNC) &_POSEIDON_upd_RHO_cpp_fusion_onlyPotts, 11},
    {"_POSEIDON_upd_Vk_cpp", (DL_FUNC) &_POSEIDON_upd_Vk_cpp, 3},
    {"_POSEIDON_elbo_diff_R_fusion", (DL_FUNC) &_POSEIDON_elbo_diff_R_fusion, 3},
    {"_POSEIDON_elbo_p_Y_fusion", (DL_FUNC) &_POSEIDON_elbo_p_Y_fusion, 5},
    {"_POSEIDON_POSEIDON_cpp_fiSAN", (DL_FUNC) &_POSEIDON_POSEIDON_cpp_fiSAN, 18},
    {"_POSEIDON_POSEIDON_cpp_onlyPotts", (DL_FUNC) &_POSEIDON_POSEIDON_cpp_onlyPotts, 16},
    {"_POSEIDON_POSEIDON_cpp_onlyfiSAN", (DL_FUNC) &_POSEIDON_POSEIDON_cpp_onlyfiSAN, 15},
    {"_POSEIDON_EQ66", (DL_FUNC) &_POSEIDON_EQ66, 2},
    {"_POSEIDON_p_MF", (DL_FUNC) &_POSEIDON_p_MF, 3},
    {"_POSEIDON_create_pMF", (DL_FUNC) &_POSEIDON_create_pMF, 3},
    {"_POSEIDON_bisection_LU2", (DL_FUNC) &_POSEIDON_bisection_LU2, 6},
    {"_POSEIDON_est_itemp_PL2", (DL_FUNC) &_POSEIDON_est_itemp_PL2, 3},
    {"_POSEIDON_est_itemp_PL2_withpi", (DL_FUNC) &_POSEIDON_est_itemp_PL2_withpi, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_POSEIDON(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
